on: [push]

jobs:
  hello_arborist:
    runs-on: ubuntu-latest
    name: Introduce the Arborist!
    steps:
      - name: Arborist
        id: arborist
        uses: term-world/arborist@test
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
