on: [push]

permissions:
  contents: read
  repository-projects: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Introduce the Arborist!
    steps:
      - name: Arborist
        id: arborist
        uses: term-world/arborist@v0.49.6
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
